# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=7046

### Create work order for broken coffee machine
POST https://{{hostname}}:{{port}}/CoffeeMachineWorkOrder/IsBroken
Content-Type: application/json

{
  "MachineNumber": "A000000001",
  "Description": "No coffee :(",
  "Reporter": "Peter"
}

### Assign repairman to work order
POST https://{{hostname}}:{{port}}/CoffeeMachineWorkOrder/AssignRepairman
Content-Type: application/json

{
  "WorkOrderId": "ab8a2f09-bd74-411b-81b2-a717a284b0f9",
  "repairman": "worker"
}


### Repair Completed
POST https://{{hostname}}:{{port}}/CoffeeMachineWorkOrder/RepairCompleted
Content-Type: application/json

{
  "WorkOrderId" : "ab8a2f09-bd74-411b-81b2-a717a284b0f9"
}

### Get work order for broken coffee machine
GET https://{{hostname}}:{{port}}/CoffeeMachineWorkOrder/ab8a2f09-bd74-411b-81b2-a717a284b0f9